# Generated by Django 5.2.17 on 2026-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="alias",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
