# Generated by Django 5.2.17 on 2026-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
