# Generated by Django 6.1 on 2026-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_guest_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.PositiveIntegerField(help_text='The id the account had before it was deleted - not a live foreign key.')),
                ('username', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=12)),
                ('rank', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture_path', models.CharField(blank=True, max_length=255)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='How many forum reactions they had at the moment of expiry.')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
