# Generated by Django 6.1 on 2026-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_guestarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.IntegerField(default=0),
        ),
    ]
