# Generated by Django 6.1 on 2026-09-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='online', max_length=20),
        ),
    ]
