# Generated by Django 6.1 on 2026-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_cutscene_mode',
            field=models.CharField(choices=[('always', 'Every time'), ('cooldown', '10 minute cooldown'), ('never', 'Never')], default='cooldown', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
