# Generated by Django 6.1 on 2026-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_mail_cutscene_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret_cutscene_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
