# Generated by Django 6.1 on 2026-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_secret_cutscene_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_first_login',
            field=models.BooleanField(default=False),
        ),
    ]
