# Generated by Django 6.1 on 2026-10-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tokengrantlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gift', 'Gift'), ('purchase', 'Purchase'), ('won', 'Won'), ('admin_grant', 'Admin Grant'), ('spent', 'Spent')], max_length=20)),
                ('amount', models.IntegerField(help_text='Signed - positive for earned, negative for spent.')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
