# Generated by Django 6.1 on 2026-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tokentransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vip_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
