# Generated by Django 6.1 on 2026-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_vip_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site_theme',
            field=models.CharField(choices=[('classic_red', 'Classic Red'), ('toxic_green', 'Toxic Green'), ('cyber_blue', 'Cyber Blue'), ('royal_purple', 'Royal Purple'), ('gold', 'Gold')], default='classic_red', max_length=20),
        ),
    ]
