# Generated by Django 6.1 on 2026-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_purchaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_theme',
            field=models.CharField(choices=[('none', 'None (Default)')], default='none', max_length=30),
        ),
    ]
