# Generated by Django 6.1 on 2026-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_background_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_theme',
            field=models.CharField(choices=[('none', 'None (Default)'), ('kitty', 'Kitty Background'), ('panda', 'Panda Background')], default='none', max_length=30),
        ),
    ]
