from django.urls import path

from . import views

urlpatterns = [
    path('', views.mail_inbox, name='mail_inbox'),
    path('sent/', views.mail_sent, name='mail_sent'),
    path('updates/', views.mail_updates, name='mail_updates'),
    path('update/new/', views.mail_update_new, name='mail_update_new'),
    path('directives/', views.mail_directives, name='mail_directives'),
    path('directive/new/', views.mail_directive_new, name='mail_directive_new'),
    path('admin-mail/new/', views.mail_admin_mail_new, name='mail_admin_mail_new'),
    path('fan-letters/', views.mail_fan_letters, name='mail_fan_letters'),
    path('fan-letters/new/', views.mail_fan_letter_new, name='mail_fan_letter_new'),
    path('fan-letters/page/', views.mail_fan_letters_page, name='mail_fan_letters_page'),
    path('social/', views.mail_social, name='mail_social'),
    path('social/group/new/', views.mail_group_new, name='mail_group_new'),
    path('social/dm/<str:username>/', views.mail_social_dm_start, name='mail_social_dm_start'),
    path('social/<int:conversation_id>/', views.mail_social_thread, name='mail_social_thread'),
    path('friends/', views.mail_friends, name='mail_friends'),
    path('saved/', views.mail_saved, name='mail_saved'),
    path('message/<int:message_id>/save/', views.mail_message_save, name='mail_message_save'),
    path('message/<int:message_id>/mark-read/', views.mail_message_mark_read, name='mail_message_mark_read'),
    path('message/<int:message_id>/forward/', views.mail_message_forward, name='mail_message_forward'),
    path('message/<int:message_id>/media/', views.mail_message_media, name='mail_message_media'),
    path('reports/', views.mail_reports, name='mail_reports'),
    path('reports/history/', views.mail_report_history, name='mail_report_history'),
    path('reports/<int:report_id>/resolve/', views.mail_report_resolve, name='mail_report_resolve'),
    path('moderate/<str:username>/new/', views.mail_moderation_new, name='mail_moderation_new'),
    path('moderate/<int:action_id>/lift/', views.mail_moderation_lift, name='mail_moderation_lift'),
    path('report/new/', views.mail_report_new, name='mail_report_new'),
    path('recipients/search/', views.mail_recipient_search, name='mail_recipient_search'),
    path('share/post/<int:post_id>/', views.mail_forum_share, name='mail_forum_share'),
    path('share/comment/<int:comment_id>/', views.mail_comment_share, name='mail_comment_share'),
    path('gif-search/', views.mail_gif_search, name='mail_gif_search'),
    path('relationship/<str:username>/friend/', views.mail_relationship_friend, name='mail_relationship_friend'),
    path(
        'friend-request/<int:request_id>/respond/',
        views.mail_friend_request_respond,
        name='mail_friend_request_respond',
    ),
    path('relationship/<str:username>/mute/', views.mail_relationship_mute, name='mail_relationship_mute'),
    path('relationship/<str:username>/block/', views.mail_relationship_block, name='mail_relationship_block'),
]
