# Generated by Django 6.1 on 2026-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_deleted_at_comment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_vip_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
