# Generated by Django 6.1 on 2026-09-08 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_conversation_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('bullying', 'Bullying'), ('nsfw', 'NSFW'), ('guidelines', 'Profile threatens guidelines'), ('personal_info', 'Leaking personal information')], default='guidelines', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='reports/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='kind',
            field=models.CharField(choices=[('friend', 'Friend'), ('block', 'Block'), ('mute', 'Mute')], max_length=10),
        ),
    ]
