# Generated by Django 6.1 on 2026-09-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_edited_at_comment'),
        ('mail', '0005_conversation_is_admin_only_message_forwarded_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_a_target',
        ),
        migrations.AddField(
            model_name='message',
            name='shared_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_shares', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='forum.comment'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reported_user__isnull', False), ('reported_message__isnull', False), ('reported_comment__isnull', False), _connector='OR'), name='report_has_a_target'),
        ),
    ]
