# Generated by Django 6.1 on 2026-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_message_deleted_at_message_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_via_draft',
            field=models.BooleanField(default=False),
        ),
    ]
